<a href="https://colab.research.google.com/github/shapi88/tensorflow_book/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow fundamentals 1st part notebook

Covering:
* Introduction to tensors
* Getting info from tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.fucntion (a way to speed up your regular python functions)
* Using GPU w/ tensors or TSU
* Exercises


### Topics
**1** - What is deep learning

**2** - Why use deep learning

**3** - What are neural networks

**4** - What is deep learning already being used for

**5** - What is and why use tensor flow

**6** - What is a Tensor

**7** - TensorFlow and tf.constant()

**8** - TensorFlow and tf.Variable()

**9** - Creating tensors from NumPy arrays

**10** - Getting information from your tensors (tensor attributes)

**11** - Indexing and expanding tensors

**12** - Manipulating tensors with basic Operations

**13** - Matrix Multiplications

**14** - Changing the datatype of tensors

**15** - Tensor aggregation

**16** - Troubleshooting datatypes updates

**17** - Finding the positional minimum and maximum of a tensor

**18** - Squeezing a tensor

**19** - One-hot encoding tensor

**20** - Trying out more tensor math operations

**21** - Exploring TensorFlow and NumPy's compatibility

**22** - Operations on GPUs

**23** - TensorFlow fundamentals challenge

In [ ]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

# https://www.tensorflow.org/api_docs/python/tf/constant
# create tensors w/ tf.constant()
scalar = tf.constant(7) # <tf.Tensor: shape=(), dtype=int32, numpy=7>
scalar

# check the number of dimensions of a tensor (ndim stands for the number of dimensions)
scalar.ndim

2.12.0


0

In [ ]:
vector = tf.constant([1, 2, 3, 4, 5, 6]) # <tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
vector.ndim, vector

(1,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>)

In [ ]:
matrix = tf.constant([[10,101],[2,3]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 10, 101],
        [  2,   3]], dtype=int32)>,
 2)

In [ ]:
#create another matrix 
another_matrix = tf.constant([[1., 3.],
                              [3.9, 9.1],
                              [0.9, 0.3]], dtype=tf.float16)
another_matrix, another_matrix.ndim


(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1. , 3. ],
        [3.9, 9.1],
        [0.9, 0.3]], dtype=float16)>,
 2)

In [ ]:
tensor = tf.constant([ [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], ]) 
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# Create a random tensor
# Random tensors are tensors of some arbitrary size which contains random numbers

random_1 = tf.random.Generator.from_seed(42) # set seed to reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([
    [2, 7],
    [3, 10],
    [2, 5]
])
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  7],
        [ 3, 10],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3, 10],
        [ 2,  5],
        [ 2,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [ True, False]])>)

In [ ]:
# Shuffle a tensor with a seed of 42
not_shuffled = tf.constant([
    [2, 7],
    [3, 10],
    [2, 5]
])

tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
not_shuffled, shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  7],
        [ 3, 10],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  7],
        [ 3, 10],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

🛠 **Exercise** Read through Tensorflow documentation on random seed generator:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and pratice writing 5 random tensors.

### Documentation on tensorflow set_seed:
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

> **Rule 1**: If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

> **Rule 2**: If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

> **Rule 3**: If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

> **Rule 4**: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
#exercise 1 - create a operation level seed only
not_shuffled = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

seed = tf.random.get_global_generator()
shuffled_with_op_level = tf.random.shuffle(not_shuffled, seed=1)
seed, shuffled_with_op_level, not_shuffled, not_shuffled == shuffled_with_op_level

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7fba41d13850>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [False, False],
        [False, False]])>)

In [ ]:
#exercise 2 - create a global seed only
not_shuffled = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

tf.random.set_seed(1)
shuffled = tf.random.shuffle(not_shuffled)
shuffled, not_shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [False, False],
        [False, False]])>)

In [ ]:
#exercise 3 - create a global seed and operation level seed
not_shuffled = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

tf.random.set_seed(1)
shuffled = tf.random.shuffle(not_shuffled, seed=10)
shuffled, not_shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
#exercise 4 - create a global seed and operation level seed and a none operation level seed
not_shuffled = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

tf.random.set_seed(1)
shuffled_with_op_level = tf.random.shuffle(not_shuffled, seed=10)
shuffled = tf.random.shuffle(not_shuffled)
shuffled_with_op_level, shuffled, not_shuffled, not_shuffled == shuffled_with_op_level, not_shuffled == shuffled, shuffled == shuffled_with_op_level

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [5, 6],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [ True,  True],
        [False, False]])>)

In [ ]:
#exercise 5 - testing tensor uniform examples
tf.random.set_seed(1234)
uniform_1 = tf.random.uniform(    
    [1, 2],
    [3, 4],
    [5, 6])
# uniform 2 and uniform 3 will have different values beacuse they use different operation level seeds
uniform_2 = tf.random.uniform([1])
uniform_3 = tf.random.uniform([1])
uniform_1, uniform_2, uniform_3

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.0760784, 4.7292376]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.3253647], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.59750986], dtype=float32)>)

In [ ]:
#exercise 5 - testing tensor uniform examples with tensorflow notation methods

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

g(), f(), g(), f()


#1ST OUPUT
#((<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>),
# (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.829064], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.23841548], dtype=float32)>))

#2ND OUPUT without seed
#((<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>),
# (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>))

#3RD OUPUT with global seed affects both methods
#((<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.81269646], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05554414], dtype=float32)>),
# (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.81269646], dtype=float32)>,
#  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.05554414], dtype=float32)>))

((<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>,
  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>),
 (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>,
  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>),
 (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>,
  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>),
 (<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>,
  <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>))

# Motivation behind shuffling the data in the dataset
* Shuffling the data in a dataset can reduce the likelihood of the model learning patterns that are specific to the order of the data in the dataset.

* Shuffling the data can increase the randomness and variety of the data seen by the model during training.

* By shuffling the data, the model sees a more diverse set of examples during each epoch of training, which can help it learn more generalizable patterns that can be applied to new, unseen data.

* Shuffling the data can be especially important when the data has a particular order, such as time series data or sorted data.

* In TensorFlow, the `tf.data.Dataset.shuffle()` method can be used to shuffle the data in a dataset, which can be more memory-efficient and faster than shuffling the data outside of TensorFlow.

* The `tf.data.Dataset.shuffle()` method takes an argument buffer_size, which specifies the number of elements from the dataset to use for shuffling. A larger buffer_size can result in a more randomized shuffle, but may also increase the memory usage and the time required to shuffle the data.

* By default, the `tf.data.Dataset.shuffle()` method uses a random seed to ensure that the order of the shuffled data is the same across different runs of the program, unless a seed is explicitly specified.

# Other way to produce tensors
https://numpy.org/doc/stable/reference/index.html

In [ ]:
tf.ones([3,3]), tf.ones([3,3], dtype=tf.int32), tf.ones([3, 3, 3], dtype=tf.int32)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=int32)>)

In [ ]:
tf.zeros([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np

array_1 = np.arange(1, 25, dtype=np.int32)
array_1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_like_array_1 = tf.constant(array_1, shape=(8,3))
tensor_like_array_1

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

# Getting Dimensions from tensors
* Shape 

```
tensor.shape
```


* Rank

```
tensor.ndim
```
* Axis or dimension

```
tensor[0], tensor[1]
```
* Size

```
tf.size(tensor)
```


In [ ]:
# create a 4 dimension tensor
four_dim_tensor = tf.zeros(shape=[2,3,4,5])
four_dim_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
four_dim_tensor[0][0][0][0], four_dim_tensor[0][0][0], four_dim_tensor[0][0], four_dim_tensor[0]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>)

In [ ]:
tf.size(four_dim_tensor), four_dim_tensor.ndim, four_dim_tensor.shape, four_dim_tensor 

(<tf.Tensor: shape=(), dtype=int32, numpy=120>,
 4,
 TensorShape([2, 3, 4, 5]),
 <tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [ ]:
# Getting ifnormation from a tensor
print("Datatype of the tensor: ", four_dim_tensor.dtype)
print("Number of dimensions (rank): ", four_dim_tensor.ndim)
print("Shape of the tensor: ", four_dim_tensor.shape)
print("Element along zero Axis: ", four_dim_tensor.shape[0])
print("Element along last Axis: ", four_dim_tensor.shape[-1])
#print("First elemen: t", four_dim_tensor[0])
#print("Tensor size (total number of elements): ", tf.size(four_dim_tensor))
print("Tensor size (total number of elements using numpy): ", tf.size(four_dim_tensor).numpy())

Datatype of the tensor:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Element along zero Axis:  2
Element along last Axis:  5
Tensor size (total number of elements using numpy):  120


# Indexing Tensors
Tensors can be indexed just like python lists

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
big_tensor = [[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]]
# big_tensor[:2, :2, :2, :2] # TypeError: list indices must be integers or slices, not tuple

In [ ]:
four_dim_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Indexing tensors
four_dim_tensor[:2, :2, :2, :2].numpy()

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)

In [ ]:
# create a rank 2 tensor
rank_2_tensor_zeros = tf.zeros(shape=[3,3])
rank_2_tensor = tf.constant([
    [1,2],
    [3,4]
])
rank_2_tensor_zeros, rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 2,
 TensorShape([2, 2]))

In [ ]:
# get the last item of each row of the tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# add in an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
rank_3_tensor_alt = tf.expand_dims(rank_2_tensor, axis=-1) # -1 expands final axis
rank_3_tensor_alt

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Expand 0-axis  
rank_3_tensor_alt = tf.expand_dims(rank_2_tensor, axis=0) # 0 expands first axis
rank_3_tensor_alt

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

# Manipulating tensors with basic operations
**Basic Operations**
> `+,- *, /`


In [ ]:
# You can add values to a tensor using addition operator
tensor = tf.constant([
    [1, 2], 
    [3, 4]
])
(tensor * 10 + 1 - 2)/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 4.5,  9.5],
       [14.5, 19.5]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

**Matrix Multiplication**

In ML one of the most common operations is the matrix multiplication
http://matrixmultiplication.xyz/
https://www.tensorflow.org/api_docs/python/tf/linalg/matmul .

- The input tensors for matrix multiplication in TensorFlow must have a rank of at least 2.
- The inner 2 dimensions of the input tensors must specify valid matrix multiplication dimensions.
- Any further outer dimensions of the input tensors must specify matching batch sizes.
- Both matrices must be of the same type, with supported types including bfloat16, float16, float32, float64, int32, int64, complex64, and complex128.
- Either matrix can be transposed or adjointed on the fly by setting the corresponding flag to True (which is False by default).
- If one or both matrices contain many zeros, a more efficient multiplication algorithm can be used by setting the corresponding a_is_sparse or b_is_sparse flag to True (which is also False by default).
- This optimization is only available for plain matrices (rank-2 tensors) with datatypes bfloat16 or float32.

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

📖 Resource: https://www.mathsisfun.com/algebra/matrix-multiplying.html


```
X = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

Y = tf.constant([
    [4,5,6],
    [7,8,9],
    [2,22,0],
])

Z = tf.constant([
    [1,2, 4],
    [4,5, 3]
])
Z, tf.reshape(Z, (3, 2 )), tf.transpose(Z), tf.matmul(Y, tf.reshape(Z, (3, 2 )))
```



In [ ]:
X = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

Y = tf.constant([
    [4,5,6],
    [7,8,9],
    [2,22,0],
])

Z = tf.constant([
    [1,2, 4],
    [4,5, 3]
])

Z, tf.reshape(Z, (3, 2 )), tf.transpose(Z), tf.matmul(Y, tf.reshape(Z, (3, 2 )))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [4, 5, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 4],
        [5, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [4, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[54, 46],
        [84, 73],
        [90, 92]], dtype=int32)>)

In [ ]:
# repeat class 26
tf.tensordot(X,Y, axes=1), X@Y


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 24,  87,  24],
        [ 63, 192,  69],
        [102, 297, 114]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 24,  87,  24],
        [ 63, 192,  69],
        [102, 297, 114]], dtype=int32)>)

# Changing the datatype of a tensor

In [ ]:
A1 = tf.constant([1.1,2.2])
B1 = tf.constant([1,2])
A1.dtype, B1.dtype

(tf.float32, tf.int32)

In [ ]:
C1 = tf.cast(A1, dtype=tf.float16)
D1 = tf.cast(B1, dtype=tf.int16)
C1, C1.dtype, D1, D1.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.1, 2.2], dtype=float16)>,
 tf.float16,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>,
 tf.int16)

# Agreggation Tensors
Aggregation Tensors = condensing them from multiple valiues down to a smaller amount of values

In [ ]:
E1 = tf.constant([-1.,-2.])
tf.abs(C1), C1, tf.abs(E1), E1

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.1, 2.2], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.1, 2.2], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1., -2.], dtype=float32)>)

Let's go though the following forms of aggregation:
- get the minimum
- get the maximum
- get the sum of a tensor
- get the mean of a tensor

E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 67, 45, 91, 57, 40, 11, 78, 53, 51, 73, 79, 74,  4, 43, 18,  5,
       64, 86, 70, 65, 54, 68, 93, 37, 43,  1, 80, 32, 18, 72, 19, 79, 41,
       76, 13, 17, 76, 18, 60, 69, 73, 24, 13, 98,  7, 93, 42, 57,  8])>

In [ ]:
tf.size(E), E.ndim, E.shape, np.min(E), tf.reduce_min(E), np.max(E), np.mean(E), np.sum(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 1,
 TensorShape([50]),
 1,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 98,
 49.16,
 2458,
 <tf.Tensor: shape=(), dtype=int64, numpy=2458>)

In [ ]:
F = tf.constant([np.random.randint(0, 100, size=3), np.random.randint(0, 100, size=3)])
F

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48,  6,  3],
       [16, 52, 52]], dtype=int32)>

In [ ]:
# get variance
# needs to be complex or float values
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=465.25>

In [ ]:
# get deviation
# need to be complex or float 
tf.math.reduce_std(tf.cast(F, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=21.56>

In [ ]:
# get max value 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [ ]:
# get max from the first dimension
tf.reduce_max(F, 0), F.ndim

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([48, 52, 52], dtype=int32)>,
 2)

In [ ]:
#get the tensor variance with math and tf probability
import tensorflow_probability as tfp
tfp.stats.variance(F, None), tf.math.reduce_variance(tf.cast(F, dtype=tf.float16))

(<tf.Tensor: shape=(), dtype=int32, numpy=465>,
 <tf.Tensor: shape=(), dtype=float16, numpy=465.2>)

In [ ]:
# get tensor variation from first dimension/axis
tfp.stats.variance(F, 0), tf.math.reduce_variance(tf.cast(F, dtype=tf.float16), 0)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([256, 529, 600], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=float16, numpy=array([256., 529., 600.], dtype=float16)>)

🛠 **Exercise** - find variance and standard deviation of our E tensor using tensoflow methods

In [ ]:
import tensorflow_probability as tfp
# find variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=821>

In [ ]:
# find standard deviation
E1 = tf.cast(E, dtype=tf.float32)
tf.math.reduce_std(E1)

<tf.Tensor: shape=(), dtype=float32, numpy=28.663816>

# Find the positional maximum and minimum

In [ ]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=(50,))
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find the positional maximum, find the positional maximum value
tf.argmax(G), G[tf.argmax(G)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
# find the max value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#check the equality
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(50,)), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape 


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One Hot enconding
📖 **Resource** - https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/

In [ ]:
some_list = [0, 1, 2]
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:

tf.one_hot(some_list, depth=3, on_value='loaded', off_value='empty')

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'loaded', b'empty', b'empty'],
       [b'empty', b'loaded', b'empty'],
       [b'empty', b'empty', b'loaded']], dtype=object)>

# Squaring, log, square root

In [ ]:
H = tf.range(0, 10, 2)
H

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  4, 16, 36, 64], dtype=int32)>

In [ ]:
tf .sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.       , 1.4142135, 2.       , 2.4494896, 2.828427 ],
      dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([     -inf, 0.6931472, 1.3862944, 1.7917595, 2.0794415],
      dtype=float32)>

# Numpy vs Tensors

🔑 **Note** - Tensorflow tensors can run on a GPU or TPU ( tensor processor unit )  then Numpy arrays (for faster numerical processing)

In [ ]:
# the default types are slightly different
numpy_J = tf.constant(np.array([1.,2.,3.]))
tensor_J = tf.constant([1.,2.,3.])
tensor_J.dtype, numpy_J.dtype

(tf.float32, tf.float64)

In [ ]:
# the default types are slightly different
numpy_J = tf.constant(np.array([1,2,3]))
tensor_J = tf.constant([1,2,3])
tensor_J.dtype, numpy_J.dtype

(tf.int32, tf.int64)

# Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
!nvidia-smi

Mon May  8 15:01:37 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    26W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 **Note** - If you have access to CUDA-enabled GPU, TensorFlow will automatically use it when its possible